

import { User, UserRole } from './types';

// Custom SVG Avatar (Data URI)
export const DEFAULT_USER_AVATAR = "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSI+PHJlY3Qgd2lkdGg9IjI0IiBoZWlnaHQ9IjI0IiBmaWxsPSIjRjFGNUY5Ii8+PHBhdGggZD0iTTEyIDEyQzE0LjIxIDEyIDE2IDEwLjIxIDE2IDhDMTYgNS43OSAxNC4yMSA0IDEyIDRDOS43OSA0IDggNS43OSA4IDhDOCAxMC4yMSA5Ljc5IDEyIDEyIDEyWk0xMiAxNEM5LjMzIDE0IDQgMTUuMzQgNCAxOFYyMEgyMFYxOEMyMCAxNS4zNCAxNC42NyAxNCAxMiAxNFoiIGZpbGw9IiNDQkQ1RTEiLz48L3N2Zz4=";

export const MOCK_USERS: User[] = [
  {
    id: 'admin-seed',
    name: 'Administrador Principal',
    email: 'admin@email.com',
    password: 'admin',
    role: UserRole.ADMIN,
    avatar: DEFAULT_USER_AVATAR,
    phone: '555-0123',
    bio: 'System Administrator',
    language: 'ES',
    status: 'ACTIVE'
  },
  {
    id: 'accountant-seed',
    name: 'Contador',
    email: 'contador@email.com',
    password: '123456',
    role: UserRole.ACCOUNTANT,
    avatar: DEFAULT_USER_AVATAR,
    phone: '555-0456',
    bio: 'Staff Accountant',
    language: 'ES',
    status: 'ACTIVE'
  },
  {
    id: 'viewer-seed',
    name: 'Auditor',
    email: 'viewer',
    password: '123456',
    role: UserRole.VIEWER,
    avatar: DEFAULT_USER_AVATAR,
    phone: '555-0789',
    bio: 'External Auditor',
    language: 'ES',
    status: 'ACTIVE'
  }
];

// Used only for initial seeding if local storage is empty
export const SEED_USERS: User[] = MOCK_USERS;

export const APP_NAME = "FinMakes";

export const TRANSLATIONS: any = {
  EN: {
    // Sidebar
    'dashboard': 'Dashboard',
    'movements': 'Movements',
    'reports': 'Financial Reports',
    'settings': 'Settings',
    'notifications': 'Notifications',
    'signOut': 'Sign Out',
    'generateAdminCode': 'Generate Admin Code',
    'adminCodeDesc': 'Use this code to authorize deletions for non-admin users.',
    'codeValid5Min': 'Valid for 5 minutes.',
    
    // Login
    'welcomeBack': 'Welcome Back',
    'signInTo': 'Sign in to your account',
    'email': 'Email Address / Username',
    'password': 'Password',
    'loginButton': 'Sign In',
    'loggingIn': 'Signing in...',
    'invalidCredentials': 'Invalid username or password.',
    'demoHint': 'Default Admin:',
    'passwordPlaceholder': 'Enter your password',
    'emailPlaceholder': 'admin@email.com',
    'haveCode': 'I have an invitation code',
    'enterCode': 'Enter 4-digit Code',
    'verifyCode': 'Verify Code',
    'backToLogin': 'Back to Login',
    'codeExpired': 'This code has expired.',
    'codeInvalid': 'Invalid or expired code.',
    'registerWithCode': 'Register with Code',
    'verifying': 'Verifying...',
    'codeVerified': 'Code Verified!',

    // Dashboard
    'financialOverview': 'Financial Overview',
    'realTimeStatus': 'Real-time financial status of your business',
    'netCashBalance': 'Net Cash Balance',
    'totalIncome': 'Total Income',
    'totalExpenses': 'Total Expenses',
    'pendingReceivables': 'Pending Receivables',
    'activityDistribution': 'Activity Distribution',
    'incomeDistribution': 'Income Distribution',
    'expenseDistribution': 'Expense Distribution',
    'pendingNotifications': 'Pending Notifications',
    'noNotifications': 'No pending alerts.',
    'recentTransactions': 'Recent Transactions',
    'date': 'Date',
    'desc': 'Desc',
    'amount': 'Amount',
    'markAsRead': 'Mark as Read',

    // Transactions
    'financialMovements': 'Financial Movements',
    'manageMovements': 'Manage operational expenses, investments, and debt.',
    'allMovements': 'All Movements',
    'accountsReceivable': 'Accounts Receivable',
    'accountsPayable': 'Accounts Payable',
    'recordMovement': 'Record Movement',
    'analyzing': 'Analyzing Receipt...',
    'scanReceipt': 'Scan Receipt / Invoice',
    'autoDetect': 'Auto-detects Amount, Date & Due Date',
    'description': 'Description',
    'movementDate': 'Movement Date',
    'accountType': 'Account Type',
    'flowType': 'Flow Type',
    'paymentDetails': 'Payment Details',
    'dueDate': 'Due Date',
    'status': 'Status',
    'activityGroup': 'Activity Group',
    'saveMovement': 'Save Movement',
    'details': 'Details',
    'action': 'Action',
    'paid': 'Paid',
    'pending': 'Pending',
    'due': 'Due',
    'noTransactions': 'No transactions found in this category/range.',
    'invoicePlaceholder': 'e.g. Invoice #1024',
    'amountOption': 'Amount Type',
    'netAmount': 'Net Amount',
    'addTax': 'Add Tax (+VAT)',
    'finalAmount': 'Final Amount',
    'newTransaction': 'New Transaction',
    'confirmTransactionTitle': 'Confirm Transaction',
    'confirmTransactionMsg': 'Are you sure you want to save this transaction?',
    'transactionSaved': 'Transaction saved successfully!',
    'transactionError': 'Error saving transaction.',
    'verifyDetails': 'Please verify that the details below are correct:',
    'fillAllRequired': 'Please fill in all required fields.',
    'deleteRestricted': 'Delete Restricted',
    'deleteRestrictedMsg': 'Only Admins can delete transactions. Please enter an Admin Authorization Code to proceed.',
    'enterAdminCode': 'Enter Admin Code',
    'confirmDelete': 'Confirm Delete',
    'transactionDeleted': 'Transaction deleted successfully.',
    'invalidAdminCode': 'Invalid or expired Admin Code.',

    // Enum Translations
    'val_OPERATING': 'Operating',
    'val_INVESTING': 'Investing',
    'val_FINANCING': 'Financing',
    'val_INCOME': 'Income',
    'val_EXPENSE': 'Expense',
    'val_CASH': 'Cash',
    'val_RECEIVABLE': 'Receivable',
    'val_PAYABLE': 'Payable',
    'val_PENDING': 'Pending',
    'val_PAID': 'Paid',

    // Reports
    'financialStatements': 'Financial Statements',
    'generateReportsDesc': 'Generate AI-analyzed reports based on specific periods.',
    'periodSelection': 'Period Selection',
    'startDate': 'Start Date',
    'endDate': 'End Date',
    'generate': 'Generate Reports',
    'reportHistory': 'Report History',
    'noReports': 'No reports generated.',
    'loadingAI': 'Gemini AI is calculating ratios and analyzing data...',
    'selectRangePrompt': 'Select a date range and generate a report to view details.',
    'printPdf': 'Print / PDF',
    'statementDetails': 'Statement Details',
    'keyRatios': 'Key Financial Ratios',
    'cfoSummary': 'CFO Executive Summary',
    'generatedBy': 'Generated By',
    'generationDate': 'Generation Date',
    'authorizedSignature': 'Authorized Signature',
    'view': 'View',
    'folio': 'Folio',
    'period': 'Period',
    'type': 'Type',
    'confirmGenerateTitle': 'Confirm Generation',
    'confirmGenerateMsg': 'Are you sure you want to generate this financial statement? This will record a snapshot of the current data.',
    'cancel': 'Cancel',
    'confirm': 'Confirm',
    'transactionBreakdown': 'Transaction Breakdown',

    // Report Line Items
    'r_revenues': 'Revenues',
    'r_total_revenue': 'Total Revenue',
    'r_expenses': 'Expenses',
    'r_total_expenses': 'Total Expenses',
    'r_income_before_tax': 'Income Before Taxes',
    'r_tax_provision': 'Tax Provision',
    'r_net_income': 'Net Income',
    'r_assets': 'Assets',
    'r_cash_equivalents': 'Cash & Equivalents',
    'r_accounts_receivable': 'Accounts Receivable',
    'r_fixed_assets': 'Fixed Assets',
    'r_total_assets': 'Total Assets',
    'r_liabilities': 'Liabilities',
    'r_accounts_payable': 'Accounts Payable',
    'r_long_term_debt': 'Long Term Debt',
    'r_total_liabilities': 'Total Liabilities',
    'r_equity': 'Equity',
    'r_total_equity': 'Total Equity',
    'r_total_liab_equity': 'Total Liabilities + Equity',
    'r_op_activities': 'Net Cash from Operating Activities',
    'r_inv_activities': 'Net Cash from Investing Activities',
    'r_fin_activities': 'Net Cash from Financing Activities',
    'r_net_cash_flow': 'Net Increase/Decrease in Cash',
    
    // Ratio Names
    'ratio_gross_margin': 'Gross Margin',
    'ratio_op_margin': 'Operating Margin',
    'ratio_net_profit_margin': 'Net Profit Margin',
    'ratio_exp_revenue': 'Expense-to-Revenue',
    'ratio_tax_burden': 'Tax Burden',
    'ratio_current_ratio': 'Current Ratio',
    'ratio_debt_ratio': 'Debt Ratio',
    'ratio_debt_equity': 'Debt-to-Equity',
    'ratio_working_capital': 'Working Capital',
    'ratio_cash_ratio': 'Cash Ratio',
    'ratio_op_cash_flow': 'Operating Cash Flow Ratio',
    'ratio_free_cash_flow': 'Free Cash Flow',
    'ratio_cash_flow_cov': 'Cash Flow Coverage',
    'ratio_cash_flow_margin': 'Cash Flow Margin',
    'ratio_net_cash_change': 'Net Cash Change',

    // Settings
    'appSettings': 'Application Settings',
    'managePreferences': 'Manage your company details and preferences.',
    'companyInfo': 'Company Information',
    'editCompany': 'Edit Company',
    'configuration': 'Configuration',
    'uploadLogo': 'Upload Logo',
    'companyName': 'Company Name',
    'taxId': 'Tax ID / RFC',
    'businessAddress': 'Business Address',
    'taxRate': 'Applicable Tax Rate (%)',
    'taxRateDesc': 'Used for income tax calculations in reports.',
    'localization': 'Localization',
    'language': 'Language',
    'myProfile': 'My Profile',
    'saveChanges': 'Save Changes',
    'settingsSaved': 'Settings saved successfully!',
    'fullName': 'Full Name',
    'phone': 'Phone Number',
    'bio': 'Bio / Position',
    'security': 'Security',
    'changePassword': 'Change Password',
    'changePasswordDesc': 'We will send a 6-digit verification code to your email to verify your identity.',
    'sendCode': 'Send Verification Code',
    'verificationCode': 'Verification Code',
    'newPassword': 'New Password',
    'codeSent': 'Verification code sent!',
    'codeSentDesc': 'Please check your email (simulated in alert) for the 6-digit code.',
    'passwordChanged': 'Password changed successfully!',
    'invalidCode': 'Invalid verification code.',
    'verifyAndSave': 'Verify & Change Password',
    'users': 'Users',
    'manageUsers': 'Manage company users',
    'addUser': 'Add User',
    'role': 'Role',
    'actions': 'Actions',
    'userCreated': 'User added successfully',
    'userCreateError': 'Failed to add user',
    'userExists': 'User with this email already exists.',
    'active': 'Active',
    'inactive': 'Inactive',
    'activate': 'Activate',
    'deactivate': 'Deactivate',
    'accountInactive': 'Your account is inactive. Please contact the administrator.',
    'uploadPhoto': 'Upload Photo',
    'editProfile': 'Edit Profile',
    'confirmUpdate': 'Confirm Update',
    'confirmUpdateMsg': 'Are you sure you want to save these changes?',
    'confirmStatusMsg': 'Are you sure you want to change the status of this user?',
    'confirmRoleMsg': 'Are you sure you want to change the role of this user?',
    'save': 'Save',
    
    // Invitation
    'sendInvitation': 'Generate Invitation Code',
    'invitationSent': 'Invitation Code Generated!',
    'invitationDesc': 'Share this 4-digit code with the new user. They can use it to sign up directly (Valid for 6 hours).',
    'copyLink': 'Copy Code',
    'copied': 'Copied!',
    'close': 'Close',
    'invitationCode': 'Invitation Code',
  },
  ES: {
    // Sidebar
    'dashboard': 'Panel Principal',
    'movements': 'Movimientos',
    'reports': 'Estados Financieros',
    'settings': 'Ajustes',
    'notifications': 'Notificaciones',
    'signOut': 'Cerrar Sesión',
    'generateAdminCode': 'Generar Código Admin',
    'adminCodeDesc': 'Usa este código para autorizar eliminaciones a usuarios no-admin.',
    'codeValid5Min': 'Válido por 5 minutos.',

    // Login
    'welcomeBack': 'Bienvenido',
    'signInTo': 'Inicia sesión en tu cuenta',
    'email': 'Usuario / Correo',
    'password': 'Contraseña',
    'loginButton': 'Iniciar Sesión',
    'loggingIn': 'Entrando...',
    'invalidCredentials': 'Usuario o contraseña incorrectos.',
    'demoHint': 'Admin por defecto:',
    'passwordPlaceholder': 'Ingresa tu contraseña',
    'emailPlaceholder': 'admin@email.com',
    'haveCode': 'Tengo un código de invitación',
    'enterCode': 'Ingresa Código de 4 Dígitos',
    'verifyCode': 'Verificar Código',
    'backToLogin': 'Volver al Login',
    'codeExpired': 'Este código ha expirado.',
    'codeInvalid': 'Código inválido o expirado.',
    'registerWithCode': 'Registrarse con Código',
    'verifying': 'Verificando...',
    'codeVerified': '¡Código Verificado!',

    // Dashboard
    'financialOverview': 'Resumen Financiero',
    'realTimeStatus': 'Estado financiero en tiempo real de tu negocio',
    'netCashBalance': 'Balance de Efectivo',
    'totalIncome': 'Ingresos Totales',
    'totalExpenses': 'Egresos Totales',
    'pendingReceivables': 'Cuentas por Cobrar',
    'activityDistribution': 'Distribución de Actividad',
    'incomeDistribution': 'Distribución de Ingresos',
    'expenseDistribution': 'Distribución de Egresos',
    'pendingNotifications': 'Notificaciones Pendientes',
    'noNotifications': 'No hay alertas pendientes.',
    'recentTransactions': 'Transacciones Recientes',
    'date': 'Fecha',
    'desc': 'Desc',
    'amount': 'Importe',
    'markAsRead': 'Marcar como Leído',

    // Transactions
    'financialMovements': 'Movimientos Financieros',
    'manageMovements': 'Gestiona gastos operativos, inversiones y deudas.',
    'allMovements': 'Todos',
    'accountsReceivable': 'Cuentas por Cobrar',
    'accountsPayable': 'Cuentas por Pagar',
    'recordMovement': 'Registrar Movimiento',
    'analyzing': 'Analizando Recibo...',
    'scanReceipt': 'Escanear Recibo / Factura',
    'autoDetect': 'Detecta Importe, Fecha y Vencimiento',
    'description': 'Descripción',
    'movementDate': 'Fecha del Movimiento',
    'accountType': 'Tipo de Cuenta',
    'flowType': 'Tipo de Flujo',
    'paymentDetails': 'Detalles de Pago',
    'dueDate': 'Fecha Vencimiento',
    'status': 'Estado',
    'activityGroup': 'Grupo de Actividad',
    'saveMovement': 'Guardar Movimiento',
    'details': 'Detalles',
    'action': 'Acción',
    'paid': 'Pagado',
    'pending': 'Pendiente',
    'due': 'Vence',
    'noTransactions': 'No se encontraron movimientos en esta categoría/rango.',
    'invoicePlaceholder': 'ej. Factura #1024',
    'amountOption': 'Tipo de Importe',
    'netAmount': 'Importe Neto',
    'addTax': 'Agregar IVA',
    'finalAmount': 'Importe Final',
    'newTransaction': 'Nuevo Movimiento',
    'confirmTransactionTitle': 'Confirmar Movimiento',
    'confirmTransactionMsg': '¿Estás seguro de que deseas guardar este movimiento?',
    'transactionSaved': '¡Movimiento guardado exitosamente!',
    'transactionError': 'Error al guardar el movimiento.',
    'verifyDetails': 'Por favor verifica que los detalles a continuación sean correctos:',
    'fillAllRequired': 'Por favor complete todos los campos obligatorios.',
    'deleteRestricted': 'Eliminación Restringida',
    'deleteRestrictedMsg': 'Solo los Admins pueden eliminar movimientos. Ingresa un Código de Autorización Admin para proceder.',
    'enterAdminCode': 'Ingresa Código Admin',
    'confirmDelete': 'Confirmar Eliminación',
    'transactionDeleted': 'Movimiento eliminado exitosamente.',
    'invalidAdminCode': 'Código Admin inválido o expirado.',

    // Enum Translations
    'val_OPERATING': 'Operativo',
    'val_INVESTING': 'Inversión',
    'val_FINANCING': 'Financiero',
    'val_INCOME': 'Ingreso',
    'val_EXPENSE': 'Egreso',
    'val_CASH': 'Efectivo',
    'val_RECEIVABLE': 'Por Cobrar',
    'val_PAYABLE': 'Por Pagar',
    'val_PENDING': 'Pendiente',
    'val_PAID': 'Pagado',

    // Reports
    'financialStatements': 'Estados Financieros',
    'generateReportsDesc': 'Genera reportes analizados por IA para periodos específicos.',
    'periodSelection': 'Selección de Periodo',
    'startDate': 'Fecha Inicio',
    'endDate': 'Fecha Fin',
    'generate': 'Generar Reportes',
    'reportHistory': 'Historial de Reportes',
    'noReports': 'No hay reportes generados.',
    'loadingAI': 'Gemini AI está calculando ratios y analizando datos...',
    'selectRangePrompt': 'Selecciona un rango de fechas y genera un reporte para ver detalles.',
    'printPdf': 'Imprimir / PDF',
    'statementDetails': 'Detalles del Estado',
    'keyRatios': 'Ratios Financieros Clave',
    'cfoSummary': 'Resumen Ejecutivo del CFO',
    'generatedBy': 'Generado Por',
    'generationDate': 'Fecha de Generación',
    'authorizedSignature': 'Firma Autorizada',
    'view': 'Ver',
    'folio': 'Folio',
    'period': 'Periodo',
    'type': 'Tipo',
    'confirmGenerateTitle': 'Confirmar Generación',
    'confirmGenerateMsg': '¿Estás seguro de que deseas generar este estado financiero? Esto registrará una "foto" de los datos actuales.',
    'cancel': 'Cancelar',
    'confirm': 'Confirmar',
    'transactionBreakdown': 'Desglose de Movimientos',

    // Report Line Items
    'r_revenues': 'Ingresos',
    'r_total_revenue': 'Ingresos Totales',
    'r_expenses': 'Egresos',
    'r_total_expenses': 'Egresos Totales',
    'r_income_before_tax': 'Utilidad Antes de Impuestos',
    'r_tax_provision': 'Impuestos',
    'r_net_income': 'Utilidad Neta',
    'r_assets': 'Activos',
    'r_cash_equivalents': 'Efectivo y Equivalentes',
    'r_accounts_receivable': 'Cuentas por Cobrar',
    'r_fixed_assets': 'Activos Fijos',
    'r_total_assets': 'Total Activos',
    'r_liabilities': 'Pasivos',
    'r_accounts_payable': 'Cuentas por Pagar',
    'r_long_term_debt': 'Deuda a Largo Plazo',
    'r_total_liabilities': 'Total Pasivos',
    'r_equity': 'Patrimonio',
    'r_total_equity': 'Total Patrimonio',
    'r_total_liab_equity': 'Total Pasivos + Patrimonio',
    'r_op_activities': 'Flujo Neto de Actividades Operativas',
    'r_inv_activities': 'Flujo Neto de Actividades de Inversión',
    'r_fin_activities': 'Flujo Neto de Actividades Financieras',
    'r_net_cash_flow': 'Incremento/Disminución Neto de Efectivo',

    // Ratio Names
    'ratio_gross_margin': 'Margen Bruto',
    'ratio_op_margin': 'Margen Operativo',
    'ratio_net_profit_margin': 'Margen de Utilidad Neta',
    'ratio_exp_revenue': 'Gasto-Ingreso',
    'ratio_tax_burden': 'Carga Fiscal',
    'ratio_current_ratio': 'Ratio Corriente',
    'ratio_debt_ratio': 'Ratio de Endeudamiento',
    'ratio_debt_equity': 'Deuda-Patrimonio',
    'ratio_working_capital': 'Capital de Trabajo',
    'ratio_cash_ratio': 'Ratio de Efectivo',
    'ratio_op_cash_flow': 'Ratio Flujo Operativo',
    'ratio_free_cash_flow': 'Flujo de Caja Libre',
    'ratio_cash_flow_cov': 'Cobertura de Flujo',
    'ratio_cash_flow_margin': 'Margen de Flujo',
    'ratio_net_cash_change': 'Cambio Neto de Efectivo',

    // Settings
    'appSettings': 'Ajustes de la Aplicación',
    'managePreferences': 'Gestiona los detalles de tu empresa y preferencias.',
    'companyInfo': 'Información de la Empresa',
    'editCompany': 'Editar Empresa',
    'configuration': 'Configuración',
    'uploadLogo': 'Subir Logotipo',
    'companyName': 'Nombre de la Empresa',
    'taxId': 'RFC / Tax ID',
    'businessAddress': 'Dirección Comercial',
    'taxRate': 'Tasa de Impuesto Aplicable (%)',
    'taxRateDesc': 'Usado para cálculos de impuestos en los reportes.',
    'localization': 'Localización',
    'language': 'Idioma',
    'myProfile': 'Mi Perfil',
    'saveChanges': 'Guardar Cambios',
    'settingsSaved': '¡Ajustes guardados exitosamente!',
    'fullName': 'Nombre Completo',
    'phone': 'Teléfono',
    'bio': 'Bio / Cargo',
    'security': 'Seguridad',
    'changePassword': 'Cambiar Contraseña',
    'changePasswordDesc': 'Enviaremos un código de verificación de 6 dígitos para verificar tu identidad.',
    'sendCode': 'Enviar Código de Verificación',
    'verificationCode': 'Código de Verificación',
    'newPassword': 'Nueva Contraseña',
    'codeSent': '¡Código enviado!',
    'codeSentDesc': 'Por favor revisa tu correo (simulado en alerta) para obtener el código de 6 dígitos.',
    'passwordChanged': '¡Contraseña actualizada exitosamente!',
    'invalidCode': 'Código de verificación inválido.',
    'verifyAndSave': 'Verificar y Cambiar',
    'users': 'Usuarios',
    'manageUsers': 'Administrar usuarios de la empresa',
    'addUser': 'Agregar Usuario',
    'role': 'Rol',
    'actions': 'Acciones',
    'userCreated': 'Usuario creado exitosamente',
    'userCreateError': 'Error al crear usuario',
    'userExists': 'El usuario con este correo ya existe.',
    'active': 'Activo',
    'inactive': 'Inactivo',
    'activate': 'Activar',
    'deactivate': 'Desactivar',
    'accountInactive': 'Tu cuenta está inactiva. Contacta al administrador.',
    'uploadPhoto': 'Subir Foto',
    'editProfile': 'Editar Perfil',
    'confirmUpdate': 'Confirmar Actualización',
    'confirmUpdateMsg': '¿Estás seguro de que deseas guardar estos cambios?',
    'confirmStatusMsg': '¿Estás seguro de que deseas cambiar el estado de este usuario?',
    'confirmRoleMsg': '¿Estás seguro de que deseas cambiar el rol de este usuario?',
    'save': 'Guardar',
    
    // Invitation
    'sendInvitation': 'Generar Código de Invitación',
    'invitationSent': '¡Código de Invitación Generado!',
    'invitationDesc': 'Comparte este código de 4 dígitos con el nuevo usuario. Podrá usarlo para registrarse directamente (Válido por 6 horas).',
    'copyLink': 'Copiar Código',
    'copied': '¡Copiado!',
    'close': 'Cerrar',
    'invitationCode': 'Código de Invitación',
  }
};
